name: JSON check

on:
  push:
    paths:
      - '**.json'
  pull_request:

jobs:
  test-json-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
